// src/app/layout.js

import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

// Naya SAHI package import kiya
import NextTopLoader from 'nextjs-toploader';
import AppWrapper from "./components/AppWrapper";

const myFont = localFont({
  src: '../assets/fonts/PPWoodland-Regular.ttf',
  variable: '--font-head', // Is naam se CSS variable ban jayega
});
const myFontSecond = localFont({
  src: '../assets/fonts/PPWoodland-Regular.ttf',
  variable: '--font-head2', // Is naam se CSS variable ban jayega
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ByteWings - Technology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${myFont.variable} ${myFontSecond.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        {/* AppWrapper ko bahar rakho */}
        {/* <AppWrapper> */}
          
          {/* Naya Loader ab AppWrapper ke andar hai */}
          <NextTopLoader
            color="#0000FF"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
          />
          
          <Navbar />
          {children}
          <Footer />
            
        {/* </AppWrapper> */}
      </body>
    </html>
  );
}